<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>8a4be686-57c7-4ee6-8941-9a485c9e2936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='xui.UI.PageBar-NEXT:a:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef93bb2b-0557-41c5-93bf-aa433fe7fc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#2</value>
      <webElementGuid>db33c1b2-2e1e-4b66-b4b3-fea0e00ff690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>57301a55-f91d-4674-86bc-2b47d757457c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.PageBar-NEXT:a:</value>
      <webElementGuid>1263cd49-71be-4140-9648-ab5f2976ba79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-a xui-node-a-hover xui-pagebar-next xui-pagebar-next-hover xui-ui-btn xui-ui-btn-hover xui-uibar xui-uibar-hover xui-uigradient xui-uigradient-hover xui-uiborder-radius xui-uiborder-radius-hover xui-custom xui-custom-hover</value>
      <webElementGuid>e5a9ef8d-57b1-4ae5-9843-9a4c4ca76731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6d438f46-e1ec-4179-abeb-88b1b24306ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>53403e25-8e41-409d-addc-bf3dd9ab0d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.PageBar-NEXT:a:&quot;)</value>
      <webElementGuid>cd7be8ca-eee1-49f3-86aa-7743a98dfdf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='xui.UI.PageBar-NEXT:a:']</value>
      <webElementGuid>d1bb6bba-eb66-46f5-ae49-ebcb1ce4a715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.PageBar:a:']/a[4]</value>
      <webElementGuid>b6120a28-0a63-44ee-b49e-c3733403f16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>e9e6b5ff-084d-46e0-81f3-f6d7fdd1b873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKTIF'])[10]/following::a[4]</value>
      <webElementGuid>1548c8ca-d48f-44fc-a309-93cd40809cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YA'])[9]/following::a[4]</value>
      <webElementGuid>0bc6a27a-dba8-4551-8152-cb12e46798d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA PARAMETER DAFTAR COA'])[1]/preceding::a[3]</value>
      <webElementGuid>1cbb8c70-8122-40a3-8f34-b82c2011dd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor COA*'])[1]/preceding::a[3]</value>
      <webElementGuid>665f93ae-e228-4091-abe4-9a88ec418920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#2')]</value>
      <webElementGuid>b7273f60-7d74-4349-9ee1-0e9df1e90c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>c9875baf-31f9-4187-a86d-aa26462822c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#2' and @id = 'xui.UI.PageBar-NEXT:a:' and @title = '2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>0b72f047-2cf2-49d2-b821-f54e02628ab1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
