<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1. Copy URL berikut dan paste di Tab Br_6170e0 (4)</name>
   <tag></tag>
   <elementGuidId>fba713b9-58b6-4d32-87df-a56eef775330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:u:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1. Copy URL berikut dan paste di Tab Browser baru: chrome://flags/#enable-webrtc&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56bb6d48-b477-4015-abe2-c977795df2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>132aa164-b07a-40b8-8785-0d3706c291df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:u:</value>
      <webElementGuid>6dba917a-bcc9-4b4b-8f5d-1c4960112515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer  xui-ui-ctrl xui-ui-selectable      xui-custom</value>
      <webElementGuid>268c2b97-08dc-4ccf-9852-93370e413444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)</value>
      <webElementGuid>cb2ceff9-338e-405c-acac-cd246b8198cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:u:&quot;)</value>
      <webElementGuid>e07fa49f-cf95-43e3-b4da-50209bb5ed7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:u:']</value>
      <webElementGuid>c26ea373-45c8-492c-b4ce-4471339f0897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-PANEL:h:']/div[2]</value>
      <webElementGuid>8b434c16-a6c5-4a08-824b-f64065a5ee8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O K'])[2]/following::div[1]</value>
      <webElementGuid>889ae35c-1bb1-43b1-94f8-484971b7b871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Tidak Terdeteksi'])[1]/following::div[8]</value>
      <webElementGuid>4f3e0948-01d7-4db6-a4e3-2f257f684cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Copy URL berikut dan paste di Tab Browser baru:']/parent::*</value>
      <webElementGuid>60ffe854-73e5-4247-a748-3c5f2270eada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[17]/span/span/div[2]/div/div/div[2]</value>
      <webElementGuid>77f7067f-5daa-44ae-87ac-3ec2473847a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:u:' and (text() = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)' or . = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)')]</value>
      <webElementGuid>f365b14e-ff11-4285-8b19-ca0fd5846c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
