<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data Gagal Disimpan_xui_ak</name>
   <tag></tag>
   <elementGuidId>73c8eaf4-634e-4cf8-b670-0003d66ec4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#xui_ak</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui_ak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#xui_ak</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5413799d-fce2-49a6-b079-4313c7933075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-cover xui-custom xui-cover-modal xui-ui-unselectable</value>
      <webElementGuid>184906ed-0f73-4b94-9d83-f804a2a70851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui_ak</value>
      <webElementGuid>22eb1bcd-4f11-4c3f-920e-e7279a8c3d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui_ak&quot;)</value>
      <webElementGuid>1b742f32-9b25-40f9-b0f1-f67c091a3322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui_ak']</value>
      <webElementGuid>0cd7e369-3c03-4d72-91c6-8371049c263f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='xui_a']/div[6]</value>
      <webElementGuid>8ccbafc9-1f33-403c-9ce4-4e1dc2742424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>3f280a68-6d48-4109-9b42-ced51ab46702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui_ak']</value>
      <webElementGuid>32c13786-71bd-4479-b2df-1dc0ac601874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
