<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TTPPJK - TITIPAN  PAJAK_xui.UI.ComboI_360586 (1)</name>
   <tag></tag>
   <elementGuidId>347a8015-b66d-40f6-905b-1c55f7f7761e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xui.UI.ComboInput-INPUT:q:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;1 AMORBEBAN - GL BEBAN AMORTISASI 2 AMORPNMPG - GL PENAMPUNGAN AMORTISASI 3 BBBNGTRDEP - BEBAN BUNGA TRANSAKSI DEPOSITO 4 BBNBNGTRAN - BEBAN BUNGA BIAYA TRANSAKSI 5 BMHDIBYAR - BMH DIBAYAR 6 BYABNGADEP - BIAYA BUNGA DEPOSITO 7 BYABUNGA - BIAYA BUNGA 8 BYAPJKDEP - BIAYA PAJAK DEPOSITO 9 BYATRANDEP - BIAYA TRANSAKSI DEPOSITO 10 BYATRANS - BIAYA TRANSAKSI 11 DNDBRKDEP - DENDA BREAK DEPOSITO 12 KSDBDEP - KSD BUNGA DEPOSITO 13 KSDBYATRAN - KSD BIAYA TRANSAKSI 14 KSDBYTRDEP - KSD BIAYA TRANSAKSI DEPOSITO 15 MBHBYRDEP - BMH DIBAYAR DEPOSITO 16 SALDOKR - SALDO PRODUK 17 SALDOPJK - SALDO PAJAK 18 SALDOTUP - SALDO TUTUP 19 SLDPJKDEP - SALDO PAJAK DEPOSITO 20 SLDTTPDEP - SALDO TUTUP DEPOSITO 21 TES1 - TES1 22 TES2 - TES2 23 TTPPAJAK - TITIPAN PAJAK 24 TTPPJK - TITIPAN PAJAK&quot;i] >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3338c6a7-92d1-48f2-9394-7e83b1cb3d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e3547b5c-211f-4b9c-8f11-597cabe814b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2c8bafde-e429-4521-95ad-aa3f858db7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01f5500f-3c8d-4550-be4f-a705f14a9ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4975a254-4eac-4b66-b07b-93716a7a540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ComboInput-INPUT:q:</value>
      <webElementGuid>ec3d0cf3-a87d-456c-9487-7e0f5d27fe1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-ui-reset xui-node-input xui-comboinput-input xui-ui-ellipsis      xui-custom</value>
      <webElementGuid>d37d6e2c-e7c9-46fc-bd73-9c99f35e8f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ComboInput-INPUT:q:&quot;)</value>
      <webElementGuid>59a4be79-c81e-4e32-bd85-52b329121b18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xui.UI.ComboInput-INPUT:q:']</value>
      <webElementGuid>7005ebe1-eb8e-4759-8b0c-842c3284a59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ComboInput-WRAP:q:']/input</value>
      <webElementGuid>4d9a87f5-2a88-4015-adfc-f5446988456a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span/span/span[3]/span[2]/div/input</value>
      <webElementGuid>cc9897ea-6607-4c6c-baa7-cd28811f77ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'xui.UI.ComboInput-INPUT:q:']</value>
      <webElementGuid>9453a9f5-a6d8-4cbc-a8b1-144997d923ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
