<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TTPPJK - TITIPAN  PAJAK_xui.UI.ComboI_360586</name>
   <tag></tag>
   <elementGuidId>7f51718d-3fb5-4644-8131-ca767928c58c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xui.UI.ComboInput-INPUT:q:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;1 AMORBEBAN - GL BEBAN AMORTISASI 2 AMORPNMPG - GL PENAMPUNGAN AMORTISASI 3 BBBNGTRDEP - BEBAN BUNGA TRANSAKSI DEPOSITO 4 BBNBNGTRAN - BEBAN BUNGA BIAYA TRANSAKSI 5 BMHDIBYAR - BMH DIBAYAR 6 BYABNGADEP - BIAYA BUNGA DEPOSITO 7 BYABUNGA - BIAYA BUNGA 8 BYAPJKDEP - BIAYA PAJAK DEPOSITO 9 BYATRANDEP - BIAYA TRANSAKSI DEPOSITO 10 BYATRANS - BIAYA TRANSAKSI 11 DNDBRKDEP - DENDA BREAK DEPOSITO 12 KSDBDEP - KSD BUNGA DEPOSITO 13 KSDBYATRAN - KSD BIAYA TRANSAKSI 14 KSDBYTRDEP - KSD BIAYA TRANSAKSI DEPOSITO 15 MBHBYRDEP - BMH DIBAYAR DEPOSITO 16 SALDOKR - SALDO PRODUK 17 SALDOPJK - SALDO PAJAK 18 SALDOTUP - SALDO TUTUP 19 SLDPJKDEP - SALDO PAJAK DEPOSITO 20 SLDTTPDEP - SALDO TUTUP DEPOSITO 21 TES1 - TES1 22 TES2 - TES2 23 TTPPAJAK - TITIPAN PAJAK 24 TTPPJK - TITIPAN PAJAK&quot;i] >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2cd8722-dc71-4756-9a76-6f425e571b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>31cce8bc-1c71-413e-bb45-d8ff5c7d609e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f1c1de1a-15ed-41cd-831b-8d006231ff9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fefc884a-c1ce-4aad-a9bf-468f207eef1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>925c55c0-75a4-4e3b-bb1a-4b7e7218a45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ComboInput-INPUT:q:</value>
      <webElementGuid>17779e92-0971-4fc9-8add-1c071e72459b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-ui-reset xui-node-input xui-comboinput-input xui-ui-ellipsis      xui-custom</value>
      <webElementGuid>20271bf4-983c-4d68-8590-6dfa837799c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ComboInput-INPUT:q:&quot;)</value>
      <webElementGuid>bb59365b-b203-43d3-bbb3-e50d19915402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xui.UI.ComboInput-INPUT:q:']</value>
      <webElementGuid>c3527a27-40b1-424f-a071-ea07beebfcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ComboInput-WRAP:q:']/input</value>
      <webElementGuid>09c2a07a-e609-4842-b27d-ba1b358bb471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span/span/span[3]/span[2]/div/input</value>
      <webElementGuid>2af2f249-4943-4ea3-a84f-4de593597e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'xui.UI.ComboInput-INPUT:q:']</value>
      <webElementGuid>9fe7a331-ac58-4403-a17b-086d3644ee09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
