<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_COA_xui.UI.TreeGrid-CELLAb-r_a</name>
   <tag></tag>
   <elementGuidId>3a102fda-1634-4191-8315-68769d40ab33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.TreeGrid-CELLA:b:-r_a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.TreeGrid-CELLA\:b\:-r_a&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb474274-74eb-4550-b7d6-adf9847d564e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>34b56372-792b-4eb4-b73c-883d61f4caf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CELLA:b:-r_a</value>
      <webElementGuid>f12448ab-a5da-419a-b48c-47fd51d45acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-treegrid-cella xui-v-wrapper xui-showfocus      xui-custom</value>
      <webElementGuid>a8659e2b-25f2-4296-b515-73944ea1d64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CELLA:b:-r_a&quot;)</value>
      <webElementGuid>1c909e9e-1b2f-4948-97a0-defdac03aa5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLA:b:-r_a']</value>
      <webElementGuid>ff1e3b84-e8c6-448d-ad9c-46ba084e487c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-FCELL:b:-r_a']/span</value>
      <webElementGuid>441985f9-24ee-4438-9e5a-a026017b2ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COA'])[1]/following::span[5]</value>
      <webElementGuid>91ed8dff-583e-4523-8521-9c584ed4c2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar COA*'])[1]/following::span[22]</value>
      <webElementGuid>2a659935-fc42-4729-9ec4-86d7ba35927b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level*'])[1]/preceding::span[7035]</value>
      <webElementGuid>f3704a02-2de6-46c8-bd71-9d256abc91e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/table/tbody/tr[3]/td/div/div/div/div/div/span/span</value>
      <webElementGuid>1d1360ab-0caf-4d1c-aede-88630e56c0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.TreeGrid-CELLA:b:-r_a']</value>
      <webElementGuid>8eca5e4c-b81f-4a5b-9d91-f2e38c0e615a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
