<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Urut Berdasarkan_xui.UI.Label-ICONw</name>
   <tag></tag>
   <elementGuidId>61d9e89b-a831-4ee7-bc87-c584ba975c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Label-ICON:w:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.Label-ICON\:w\:&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c7d2c52-2d05-4048-94f5-33d543a31d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Label-ICON:w:</value>
      <webElementGuid>e9100a9d-399b-4675-a9ee-367e2d0522a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-span xui-node-span-hover xui-label-icon xui-label-icon-hover xuicon xuicon-hover fa fa-hover fa-lg fa-lg-hover fa-plus fa-plus-hover  xui-css-innerimage xui-css-innerimage-hover     xui-custom xui-custom-hover</value>
      <webElementGuid>fd367993-23e4-4263-b325-7ea6caccfac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Label-ICON:w:&quot;)</value>
      <webElementGuid>14367489-231d-4a43-91a2-260465ad0741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Label-ICON:w:']</value>
      <webElementGuid>76bbf8fd-9fa8-41dc-bd7c-070dd7f7dacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='xui.UI.Label:w:']/span[2]</value>
      <webElementGuid>911e3187-7330-4df2-8773-e093199affba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span[2]</value>
      <webElementGuid>17221d20-4605-456c-9f0a-454faec9afe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Label-ICON:w:']</value>
      <webElementGuid>09c8b385-b2e4-4377-b234-166c203d40a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
