<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Favorites (12)</name>
   <tag></tag>
   <elementGuidId>244ec56f-0cba-49c3-b6cb-4d489da6a8c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_stkMain >> internal:text=&quot;Favorites&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3aad0fc-f457-4556-a614-2baf24a4a555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Stacks-CAPTION:a:b</value>
      <webElementGuid>af4cd670-1ea7-468c-8e0e-579615a15c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-stacks-caption xui-title-node     xui-custom</value>
      <webElementGuid>ec903e45-d3f6-4259-8450-9fed3fc4341e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorites</value>
      <webElementGuid>19cc209d-f1ef-4f9f-ba56-c83143b102fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Stacks-CAPTION:a:b&quot;)</value>
      <webElementGuid>8c4021a6-bdf9-407a-9726-70b93b375646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      <webElementGuid>b2774b84-aee4-40f9-81e5-c4f4b30ae67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Stacks-IBWRAP:a:b']/span[5]</value>
      <webElementGuid>bf7d7974-2f1b-4959-9b66-14c3ab5a0e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[3]/following::span[14]</value>
      <webElementGuid>297f2748-bc07-4b3d-85ed-bfa72564577f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[2]/following::span[25]</value>
      <webElementGuid>8559b771-7a06-442b-8687-3456c57634c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferences'])[2]/preceding::span[10]</value>
      <webElementGuid>dac874d5-ee2e-45af-8562-6e4627fd651c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::span[24]</value>
      <webElementGuid>03d8fc96-4bf5-4ccf-85cf-4f58522b3c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span/div/span[5]</value>
      <webElementGuid>55ab6bab-ca59-4bcb-b8d8-a3b9de92109f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Stacks-CAPTION:a:b' and (text() = 'Favorites' or . = 'Favorites')]</value>
      <webElementGuid>d22b4e9b-180a-46b2-89ae-7310c17ac64b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
