<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BBBNGTRDEP - BEBAN BUNGA TRANSAKSI DEP_936a8b</name>
   <tag></tag>
   <elementGuidId>2686e76e-0d84-4cc1-a0a8-6f9d690210c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.TreeGrid-CELLA:b:-c_p']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.TreeGrid-CELLA\:b\:-c_p&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>532f7d84-2007-43c8-89a6-9a107c054c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>18b46b12-9f4d-4865-a7b2-05ec8bd479fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CELLA:b:-c_p</value>
      <webElementGuid>361ebf4c-453b-4020-b32b-3cd206d69f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-treegrid-cella xui-v-wrapper xui-showfocus      xui-custom</value>
      <webElementGuid>e168438f-cfdb-48d0-bba3-0c2a9412e289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CELLA:b:-c_p&quot;)</value>
      <webElementGuid>c6680c44-5397-41ac-9104-924eff59bc48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLA:b:-c_p']</value>
      <webElementGuid>76680f34-2ba0-4c5d-b159-f011b359b1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELL:b:-c_p']/span</value>
      <webElementGuid>76fe11c6-a485-4608-a2aa-8d22552b79af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BBBNGTRDEP - BEBAN BUNGA TRANSAKSI DEPOSITO'])[1]/following::span[11]</value>
      <webElementGuid>255868eb-dce6-48a0-bd78-e1f50f2cb677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMORPNMPG - GL PENAMPUNGAN AMORTISASI'])[1]/following::span[29]</value>
      <webElementGuid>edb0c402-b191-4523-9598-410f525d5702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BBNBNGTRAN - BEBAN BUNGA BIAYA TRANSAKSI'])[1]/preceding::span[5]</value>
      <webElementGuid>ea5c731f-8f9f-4d6a-8c3c-818cc029a1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BMHDIBYAR - BMH DIBAYAR'])[1]/preceding::span[23]</value>
      <webElementGuid>03670536-b580-4d93-a3ea-2a111512d88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr[3]/td[2]/div/div/div/div[4]/div/span/span</value>
      <webElementGuid>c4589d59-6668-4593-ada1-88f09e1dae46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.TreeGrid-CELLA:b:-c_p']</value>
      <webElementGuid>c0ae8586-224a-4bf6-b7cf-c72e095b7118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
