<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AMORBEBAN - GL BEBAN AMORTISASI_xui.UI_d6508f (1)</name>
   <tag></tag>
   <elementGuidId>b73901f7-43e2-4b94-8516-ff99f74a818e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.TreeGrid-CELLA:b:-c_f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.TreeGrid-CELLA\:b\:-c_f&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8784238b-b2cb-4f4c-9fc8-05f6b0daf7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>e9007fe4-2c4f-421b-a54b-fc5a44508414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CELLA:b:-c_f</value>
      <webElementGuid>f951c862-3764-43d9-a8be-dcc5a4a5712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-treegrid-cella xui-v-wrapper xui-showfocus      xui-custom</value>
      <webElementGuid>589e5c7b-2eb0-4512-af8d-775fc3234650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CELLA:b:-c_f&quot;)</value>
      <webElementGuid>e890367e-1181-4bea-aa5b-0cae98772a97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLA:b:-c_f']</value>
      <webElementGuid>041f2881-31bb-400d-8e14-1e59a7607004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELL:b:-c_f']/span</value>
      <webElementGuid>92599d6c-8c3d-4cbd-9542-663f7cf3b8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMORBEBAN - GL BEBAN AMORTISASI'])[1]/following::span[11]</value>
      <webElementGuid>d961e2fa-0731-47fb-a0cc-0c871d891ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gl_para_coa_id'])[1]/following::span[215]</value>
      <webElementGuid>c2191cdd-0588-4fb4-9674-0ca468768753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMORPNMPG - GL PENAMPUNGAN AMORTISASI'])[1]/preceding::span[5]</value>
      <webElementGuid>82637fc9-6301-4f19-ae06-6cf94c885287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BBBNGTRDEP - BEBAN BUNGA TRANSAKSI DEPOSITO'])[1]/preceding::span[23]</value>
      <webElementGuid>dd1c12b4-4331-43ee-b27c-a04bf4560786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr[3]/td[2]/div/div/div/div[2]/div/span/span</value>
      <webElementGuid>8e8b6e65-c4aa-43d1-8be9-f36572e79fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.TreeGrid-CELLA:b:-c_f']</value>
      <webElementGuid>f95d8262-0333-49ec-929e-2e385276a09a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
