<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_O K_1_2</name>
   <tag></tag>
   <elementGuidId>b62ecee3-81f5-4e9d-8a05-857fd759010e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='xlid'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;O K&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85ebbe50-b615-4dcf-a035-79fc59e166e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xlid</value>
      <webElementGuid>29176973-ef5a-4ff1-a803-26e1e1f8415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline.ok</value>
      <webElementGuid>6c091871-b3c3-4606-ab6d-5f0545589338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>O K</value>
      <webElementGuid>300a8794-8f9b-4bcb-b2d2-0c2a2a9fe387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Button-CAPTION:af:&quot;)/span[@id=&quot;xlid&quot;]</value>
      <webElementGuid>d746a6f6-6ef6-4ef6-8757-757ae060ec3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='xlid'])[20]</value>
      <webElementGuid>e015118b-f92b-49d6-a373-7a7683fc00ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Button-CAPTION:af:']/span</value>
      <webElementGuid>4f396520-bff2-4b67-890b-12c10f73717e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFORMASI'])[2]/following::span[13]</value>
      <webElementGuid>df48a48d-30dc-4943-99c1-09a5959504dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From: USER'])[1]/following::span[27]</value>
      <webElementGuid>40ad7c95-0211-4902-beba-798ad3813475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[SC0001] Berhasil simpan data.'])[1]/preceding::span[2]</value>
      <webElementGuid>18e0b165-dfa8-4acd-86ae-1193f24ad431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fail'])[1]/preceding::span[6]</value>
      <webElementGuid>11e38664-b239-43c9-9c45-b87d71439e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='O K']/parent::*</value>
      <webElementGuid>506fcbe7-f8a3-4274-b4e7-91d5837e15ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]/span</value>
      <webElementGuid>76087d4a-97c0-4c04-834f-e989920b098f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xlid' and (text() = 'O K' or . = 'O K')]</value>
      <webElementGuid>c6fe7d5e-31d1-4e80-a9d0-f62d485d6d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
