<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Non Aktifkan Kantor_xui.UI.CheckBox-FOCUSd</name>
   <tag></tag>
   <elementGuidId>42e34b69-237d-4f7c-87b0-1571bcb6c8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.CheckBox-FOCUS:d:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.CheckBox-FOCUS\:d\:&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>76e7b426-5097-4612-8ec4-bf2b7f323462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>3443addb-6530-4bd5-8660-b402d931aaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.CheckBox-FOCUS:d:</value>
      <webElementGuid>65e70491-1124-4928-a673-9b2de1b3c6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-checkbox-focus     xui-custom</value>
      <webElementGuid>cf66965b-e6a4-4f92-9b69-319be8350c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.CheckBox-FOCUS:d:&quot;)</value>
      <webElementGuid>312e5475-320b-44d3-a823-c78da700c248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.CheckBox-FOCUS:d:']</value>
      <webElementGuid>2c154ca4-8b83-4894-b38b-93e24e1f0270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.CheckBox:d:']/span[2]</value>
      <webElementGuid>895fb76d-1af6-4415-bf71-0d133a9208ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Aktifkan Kantor'])[1]/following::span[3]</value>
      <webElementGuid>29ca2eac-ff28-4afd-99c2-3676ea2f616b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor*'])[1]/following::span[10]</value>
      <webElementGuid>744caec6-76bf-4890-ba8d-060f31270fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Kantor'])[1]/preceding::span[11]</value>
      <webElementGuid>1040be8f-6859-4953-bbac-5065419df6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor'])[1]/preceding::span[15]</value>
      <webElementGuid>38c1afd7-5090-4c1f-b4eb-cf98695a5acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span[2]</value>
      <webElementGuid>ae3be4ce-56d8-4db4-88f6-eebf619e1240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.CheckBox-FOCUS:d:']</value>
      <webElementGuid>7949e458-d1d2-499f-8975-d30f9a498fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
