<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1. Copy URL berikut dan paste di Tab Br_6170e0</name>
   <tag></tag>
   <elementGuidId>c4d26754-823e-4e40-95d4-fda74939c144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:u:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1. Copy URL berikut dan paste di Tab Browser baru: chrome://flags/#enable-webrtc&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c61acb8-f04a-4b23-ab90-f4a35b46a04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f9acb42a-2a65-4c06-aa54-fc5b4c4c2ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:u:</value>
      <webElementGuid>b208b988-9fa6-43cb-ad43-79f81b79751a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer  xui-ui-ctrl xui-ui-selectable      xui-custom</value>
      <webElementGuid>f4b7a7f7-b99a-4bd0-86cd-9973bc9b45a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)</value>
      <webElementGuid>72aa6719-3e85-44d8-ac50-cb035fab7a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:u:&quot;)</value>
      <webElementGuid>e0bfe9cb-f875-40a8-a8b2-b99f00c357ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:u:']</value>
      <webElementGuid>de9ea412-edeb-4ca0-9cfa-5dbefafbe4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Dialog-PANEL:h:']/div[2]</value>
      <webElementGuid>c17af498-9145-4363-90ad-2b8125dd9bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O K'])[2]/following::div[1]</value>
      <webElementGuid>3325b68c-fc21-4e74-a2f6-48bedf05d0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IP Tidak Terdeteksi'])[1]/following::div[8]</value>
      <webElementGuid>795f8573-ef66-4980-a324-5bdc86448744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Copy URL berikut dan paste di Tab Browser baru:']/parent::*</value>
      <webElementGuid>2ee8ab89-be68-422a-bd17-d8b5b1629c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[17]/span/span/div[2]/div/div/div[2]</value>
      <webElementGuid>81ddee5b-90c8-4e1f-9c54-d877b5178787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:u:' and (text() = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)' or . = '1. Copy URL berikut dan paste di Tab Browser baru:    chrome://flags/#enable-webrtc-hide-local-ips-with-mdns2. Pada bagian Anonymize local IPs exposed by WebRTC.    Pilih Disabled3. Restart Browser (tutup dan buka kembali)')]</value>
      <webElementGuid>7fedf022-7c8d-4dff-ba01-caa26f75cf53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
