<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_g_idPERSETUJUAN PARAMETER DAFTAR COAPen_c573e8</name>
   <tag></tag>
   <elementGuidId>4052f02d-2126-4cfe-b26e-3dde5773ca4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:af:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;g_idPERSETUJUAN PARAMETER DAFTAR COAPencarianTampil10Urut BerdasarkanTanggal Dib&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19c962ed-e670-4db6-ae1a-f1087ab25419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1d627a4f-6dc9-4a2b-a531-440b4bc956e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:af:</value>
      <webElementGuid>3ec79623-2a0f-4619-92be-a4184d3f3e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer xui-ui-ctrl xui-ui-selectable xui-custom xui-css-noscrollx</value>
      <webElementGuid>f29381b5-442b-4e2a-9d32-07671dfd4550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>g_idPERSETUJUAN PARAMETER DAFTAR COAPencarianTampilUrut BerdasarkanNoAktivitasNo. COANama COAJenisSaldoNormalGolonganLevelIndukSeluruhKantorTanggalKadaluarsaTanggalDibuatWaktuDibuatDibuatOlehid1TAMBAH11262006KEN TESTHEADERDEBETA - ASSET210000000 - AKTIVA LANCARTIDAK26/08/202515:31:24HUBERTUS25624 1....02....1Data BaruData BaruData LamaDATA PERSETUJUAN PARAMETER DAFTAR COANomor COA*11262006Golongan*A - ASSETNama COA*KEN TESTJenis*HEADERInduk*10000000 - AKTIVA LANCARSaldo Normal*DEBETTanggal KadaluarsaLimitTIDAKSub COATIDAKLevel*2Seluruh Kantor*TIDAKKomentar TerakhirKomentarOlehKSDTIDAKSimpan KomentarTolakSetuju</value>
      <webElementGuid>01e27b38-434d-4ee1-ac97-a03363d07399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:af:&quot;)</value>
      <webElementGuid>b6ebe3ee-2007-40e9-b443-590ee2aa9858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:af:']</value>
      <webElementGuid>f82f51e6-3a7a-4d33-948b-8f374a8fbfea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Block-PANEL:t:']/div</value>
      <webElementGuid>03d0f7d4-5e05-4b8d-9e82-73933b4317b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERSETUJUAN PARAMETER DAFTAR COA'])[1]/following::div[8]</value>
      <webElementGuid>56b8f9b0-8b41-40bc-888b-0f1d64ee5eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::div[11]</value>
      <webElementGuid>a2ea2ab8-1607-4e95-a66c-22e61a0594c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/div[2]/div/div/span/span/span/div[2]/div</value>
      <webElementGuid>05130e3a-ed74-400d-a2b2-7f5bbcc004c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:af:' and (text() = 'g_idPERSETUJUAN PARAMETER DAFTAR COAPencarianTampilUrut BerdasarkanNoAktivitasNo. COANama COAJenisSaldoNormalGolonganLevelIndukSeluruhKantorTanggalKadaluarsaTanggalDibuatWaktuDibuatDibuatOlehid1TAMBAH11262006KEN TESTHEADERDEBETA - ASSET210000000 - AKTIVA LANCARTIDAK26/08/202515:31:24HUBERTUS25624 1....02....1Data BaruData BaruData LamaDATA PERSETUJUAN PARAMETER DAFTAR COANomor COA*11262006Golongan*A - ASSETNama COA*KEN TESTJenis*HEADERInduk*10000000 - AKTIVA LANCARSaldo Normal*DEBETTanggal KadaluarsaLimitTIDAKSub COATIDAKLevel*2Seluruh Kantor*TIDAKKomentar TerakhirKomentarOlehKSDTIDAKSimpan KomentarTolakSetuju' or . = 'g_idPERSETUJUAN PARAMETER DAFTAR COAPencarianTampilUrut BerdasarkanNoAktivitasNo. COANama COAJenisSaldoNormalGolonganLevelIndukSeluruhKantorTanggalKadaluarsaTanggalDibuatWaktuDibuatDibuatOlehid1TAMBAH11262006KEN TESTHEADERDEBETA - ASSET210000000 - AKTIVA LANCARTIDAK26/08/202515:31:24HUBERTUS25624 1....02....1Data BaruData BaruData LamaDATA PERSETUJUAN PARAMETER DAFTAR COANomor COA*11262006Golongan*A - ASSETNama COA*KEN TESTJenis*HEADERInduk*10000000 - AKTIVA LANCARSaldo Normal*DEBETTanggal KadaluarsaLimitTIDAKSub COATIDAKLevel*2Seluruh Kantor*TIDAKKomentar TerakhirKomentarOlehKSDTIDAKSimpan KomentarTolakSetuju')]</value>
      <webElementGuid>6d0332f8-fb45-4028-8d79-14ac8734a275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
