<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_xui.UI.ComboInput-INPUTj</name>
   <tag></tag>
   <elementGuidId>ec8523f8-2e71-4442-abec-f27431061531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xui.UI.ComboInput-INPUT:j:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[type=&quot;password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35b79090-4971-49ee-b497-ec3ff9dd3c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f657ad53-ebc6-4e94-9ef3-85cb1a2c744d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a8f72c7e-8f64-4472-8d50-c23aba765c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d7c7a868-7d92-4b10-96aa-22a813922569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9b0b22d-b2a8-4ce8-b810-19115bf5ab85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ComboInput-INPUT:j:</value>
      <webElementGuid>8afde9b2-9823-49df-8859-10d4454f9770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-ui-reset xui-node-input xui-comboinput-input xui-ui-ellipsis      xui-custom</value>
      <webElementGuid>fd92d5e1-fb16-43fb-9c04-4672966d9d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ComboInput-INPUT:j:&quot;)</value>
      <webElementGuid>ddee7bd8-3162-44a8-a279-d25d41715934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xui.UI.ComboInput-INPUT:j:']</value>
      <webElementGuid>045cd4b9-6c1a-4730-95b0-b2ea8f4ee2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.ComboInput-WRAP:j:']/input</value>
      <webElementGuid>d5f9c594-39ed-4dbc-b568-68eb9c6deac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span[3]/span/span[3]/span[2]/div/input</value>
      <webElementGuid>9678f6dc-fbdd-47c9-bef5-295c0cdc819c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'xui.UI.ComboInput-INPUT:j:']</value>
      <webElementGuid>a4f71937-3022-4a08-a900-602d9dcb39a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
